#! /usr/bin/php
<?php
  /**
   * Add application controllers
   *
   * @author Kinch Zhang <kinch.zhang@gmail.com>
   */

  if( 3 > $argc ){
    # Show help info
    echo "Usage: controller [GROUP] [CONTROLLER]... \n";
	echo "Add CONTROLLER(s) to a GROUP.\n\n";
	echo "Report bugs to <kinch.zhang@gmail.com>.\n";
  }else{
    define('AEOLUS_HOME', dirname(dirname(__FILE__)));
    $group = $argv[1];
	$con = array_slice($argv, 2);
	$group_path = AEOLUS_HOME.'/app/'.$group;

	if( file_exists( $group_path ) && is_writable($group_path) ){
	  # Process each controller
	  foreach($con as $controller){
	    $controller_path = AEOLUS_HOME.'/app/'.$group.'/controller/'.$controller.'.php';
	    if(! file_exists($controller_path)){
	      if( $res = fopen($controller_path,'w')){
		    $content = "<?php if(! defined('AEOLUS_STARTED')){ die('<h3>BAD REQUEST</h3>');}";
		    $content .= "\n  /**\n   * '$controller' controller in ";
		    $content .= "'$group' group\n   *\n   */\n\n  function ";
		    $content .= "$controller()\n  {\n    echo 'Hello,world! [From $controller";
		    $content .= " controller in \'$group\' group]';\n  }\n?>";

		    if( FALSE === fwrite($res,$content) ){
		      echo "[ERROR] Can't write content to '$controller_path'.\n";
		    }

		  }else{
		    echo "[ERROR] Can't open file '$controller_path' to write.\n";
		  }
	    }
      }
	}else{
      echo "[ERROR] The directory '$group_path' doesn't exist or doesn't allow creating files.\n";
	}
  }
