#! /usr/bin/php
<?php
  /**
   * Add application models
   *
   * @author Kinch Zhang <kinch.zhang@gmail.com>
   */

  if( 3 > $argc ){
    echo "Usage: model [GROUP] [MODEL]...\n";
	echo "Add MODEL(s) to a GROUP.\n\n";
	echo "Report bugs to <kinch.zhang@gmail.com>.\n";
  }else{
    define('AEOLUS_HOME', dirname(dirname(__FILE__)));
    $group = $argv[1];
	$models = array_slice($argv, 2);
	$group_path = AEOLUS_HOME.'/app/'.$group;
	if( file_exists( $group_path ) && is_writable($group_path) ){
	  foreach($models as $model){
	    $model_path = $group_path.'/model/'.$model.'.php';
	    if(! file_exists($model_path)){
	      if( $res = fopen($model_path,'w')){
		    $content = "<?php\n\n  # '$model' model in '$group' group\n  ";
			$content .= "class $model extends AModel\n  {\n    ";
		    $content .= "public function foobar()\n    {\n    }\n  } \n?>";

		    if( FALSE === fwrite($res,$content) ){
		      echo "[ERROR] Can't write content to '$model_path'.\n";
		    }

		  }else{
		    echo "[ERROR] Can't open file '$model_path' to write.\n";
		  }
	    }
      }
	}else{
      echo "[ERROR] Directory '$group_path' doesn't exist or doesn't allow creating files.\n";
	}
  }
?>
