#! /usr/bin/php
<?php
  /**
   * Add application views
   *
   * @author Kinch Zhang <kinch.zhang@gmail.com>
   */

  if( 3 > $argc ){
    echo "Usage: view [GROUP] [VIEW]...\n";
	echo "Add VIEW(s) to a GROUP.\n\n";
	echo "Report bugs to <kinch.zhang@gmail.com>.\n";
  }else{
    define('AEOLUS_HOME', dirname(dirname(__FILE__)));
    $group = $argv[1];
	$views = array_slice($argv, 2);
	$group_path = AEOLUS_HOME.'/app/'.$group;

	if( file_exists( $group_path ) && is_writable($group_path) ){
	  foreach( $views as $view){
	    $view_path = $group_path.'/view/'.$view.'.php';
	    if(! file_exists($view_path)){
	      if( $res = fopen($view_path,'w')){
		    $content = "<?php if(! defined('AEOLUS_STARTED')){ die('<h3>BAD REQUEST</h3>');}";
		    $content .= "\n  /**\n   * $view view class in ";
		    $content .= "'$group' group\n   *\n   */\n\n  class ";
		    $content .= $view." extends AView\n  {";
		    $content .= "\n    public function showSidebar()\n    {\n    }\n";
		    $content .= "\n    public function showContent()\n    {\n    }\n";
		    $content .= "\n    public function showScript()\n    {";
		    $content .= "\n      ?>\n      <?php\n    }\n";
		    $content .= "  }\n?>";

		    if( FALSE === fwrite($res,$content) ){
		      echo "[ERROR] Can't write content to '$view_path'.\n";
		    }

		  }else{
		    echo "[ERROR] Can't open file $view_path to write.\n";
		  }
	    }
      }
	}else{
      echo "[ERROR] The directory '$group_path' doesn't exist or doesn't allow creating files.\n";
	}
  }
?>
